package com.yfy.dianping.dal;

import com.yfy.dianping.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    ShopModel selectByPrimaryKey(Integer id);
    List<ShopModel> selectAll();
    Integer countAllShop();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Mar 01 01:10:28 CST 2020
     */
    int updateByPrimaryKey(ShopModel record);

    List<ShopModel> recommend(@Param("longitude")BigDecimal longitude,
                              @Param("latitude")BigDecimal latitude);

    List<ShopModel> search(@Param("longitude")BigDecimal longitude,
                              @Param("latitude")BigDecimal latitude,
                           @Param("keyword")String keyword);
}